'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { adminApi } from '@/lib/api';
import { SafetyReport } from '@/types/moderation';
import { format } from 'date-fns';
import { 
  Flag, ShieldAlert, CheckCircle, XCircle, 
  MessageSquare, User, Star 
} from 'lucide-react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge'; // Assuming you have shadcn UI or similar

export default function ReportsPage() {
  const [activeTab, setActiveTab] = useState<'user_complaints' | 'astro_complaints'>('user_complaints');
  const queryClient = useQueryClient();

  // Fetch Reports based on active tab
  const { data: reports, isLoading } = useQuery({
    queryKey: ['moderation-reports', activeTab],
    queryFn: async () => {
      // If tab is 'user_complaints', we want reports created BY users
      const reporterRole = activeTab === 'user_complaints' ? 'user' : 'astrologer';
      const res = await adminApi.getModerationReports({ reporterRole, status: 'pending' });
      return res.data.data as SafetyReport[];
    }
  });

  const resolveMutation = useMutation({
    mutationFn: (id: string) => adminApi.updateReportStatus(id, 'resolved'),
    onSuccess: () => {
      toast.success('Report marked as resolved');
      queryClient.invalidateQueries({ queryKey: ['moderation-reports'] });
    }
  });

  // Action to block the REPORTED person immediately
  const blockAccusedMutation = useMutation({
    mutationFn: async (report: SafetyReport) => {
      const { id, role } = report.reportedEntity;
      if (role === 'user') {
        return adminApi.updateUserStatus(id, 'blocked', `Flagged in Report ${report.ticketId}`);
      } else {
        return adminApi.updateAstrologerStatus(id, 'blocked', `Flagged in Report ${report.ticketId}`);
      }
    },
    onSuccess: () => {
      toast.success('Entity blocked successfully');
      queryClient.invalidateQueries({ queryKey: ['moderation-reports'] });
    }
  });

  return (
    <div className="p-6 max-w-[1600px] mx-auto space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <ShieldAlert className="text-red-600" /> Trust & Safety Reports
          </h1>
          <p className="text-gray-500 mt-1">Manage flags generated by your community.</p>
        </div>
        
        {/* Tabs */}
        <div className="flex bg-gray-100 p-1 rounded-lg">
          <button
            onClick={() => setActiveTab('user_complaints')}
            className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${
              activeTab === 'user_complaints' ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-900'
            }`}
          >
            Users Reporting Astrologers
          </button>
          <button
            onClick={() => setActiveTab('astro_complaints')}
            className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${
              activeTab === 'astro_complaints' ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-900'
            }`}
          >
            Astrologers Reporting Users
          </button>
        </div>
      </div>

      <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
        <table className="w-full text-left text-sm">
          <thead className="bg-gray-50 border-b border-gray-200 text-gray-500 font-medium">
            <tr>
              <th className="px-6 py-4">Ticket ID</th>
              <th className="px-6 py-4">Reporter (Victim)</th>
              <th className="px-6 py-4">Reported (Accused)</th>
              <th className="px-6 py-4">Violation</th>
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {isLoading ? (
              <tr><td colSpan={5} className="p-8 text-center text-gray-500">Loading reports...</td></tr>
            ) : reports?.length === 0 ? (
              <tr><td colSpan={5} className="p-12 text-center text-gray-500">No pending reports found.</td></tr>
            ) : (
              reports?.map((report) => (
                <tr key={report._id} className="hover:bg-gray-50/50">
                  <td className="px-6 py-4 font-mono text-gray-500 text-xs">{report.ticketId}</td>
                  
                  {/* Reporter */}
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-600 font-bold text-xs">
                        {report.reporter.name[0]}
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{report.reporter.name}</p>
                        <span className="text-xs text-gray-500 capitalize">{report.reporter.role}</span>
                      </div>
                    </div>
                  </td>

                  {/* Reported Entity */}
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-red-100 flex items-center justify-center text-red-600 font-bold text-xs">
                        {report.reportedEntity.name[0]}
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{report.reportedEntity.name}</p>
                        <span className="text-xs text-red-500 font-medium capitalize flex items-center gap-1">
                          <Flag size={10} /> Reported {report.reportedEntity.role}
                        </span>
                      </div>
                    </div>
                  </td>

                  <td className="px-6 py-4">
                    <Badge variant="outline" className="mb-1 bg-red-50 text-red-700 border-red-200">
                      {report.reason}
                    </Badge>
                    <p className="text-gray-600 text-xs max-w-xs truncate">{report.description}</p>
                  </td>

                  <td className="px-6 py-4 text-right flex justify-end gap-2">
                    <button 
                      onClick={() => resolveMutation.mutate(report._id)}
                      className="p-2 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                      title="Mark Resolved (No Action)"
                    >
                      <CheckCircle size={18} />
                    </button>
                    <button 
                      onClick={() => {
                        if(confirm(`Block ${report.reportedEntity.name}? This will revoke their access.`)) {
                          blockAccusedMutation.mutate(report);
                        }
                      }}
                      className="p-2 text-red-400 hover:text-white hover:bg-red-600 rounded-lg transition-colors"
                      title={`Block ${report.reportedEntity.name}`}
                    >
                      <ShieldAlert size={18} />
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}